//
//  SCTPollDetails+Internal.h
//  SceytChat
//
//  Copyright © 2021 Sceyt LLC. All rights reserved.
//

#import "SCTPollDetails.h"
#import "SCTChatClient+Internal.h"

NS_ASSUME_NONNULL_BEGIN

@interface SCTPollDetails ()

/// Initialize poll details for creating a new poll (internal use only).
/// The poll ID is automatically generated by the builder.
/// @param id The poll identifier (auto-generated by builder).
/// @param name The poll question.
/// @param pollDescription Optional description.
/// @param options Array of poll options.
/// @param anonymous Whether the poll is anonymous.
/// @param allowMultipleVotes Whether multiple votes are allowed.
/// @param allowVoteRetract Whether vote retraction is allowed.
- (instancetype)initWithId:(nonnull NSString *)id
                      name:(nonnull NSString *)name
           pollDescription:(nullable NSString *)pollDescription
                   options:(nonnull NSArray<SCTPollOption *> *)options
                 anonymous:(BOOL)anonymous
       allowMultipleVotes:(BOOL)allowMultipleVotes
        allowVoteRetract:(BOOL)allowVoteRetract
NS_SWIFT_NAME(init(id:name:description:options:anonymous:allowMultipleVotes:allowVoteRetract:));

- (instancetype)initWithCppPollDetails:(const SceytChat::PollDetails &)poll;
+ (instancetype)withCppPollDetails:(const SceytChat::PollDetails &)poll;

@end

NS_ASSUME_NONNULL_END

